# Generated by Django 4.2.18 on 2025-02-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metai', models.IntegerField(verbose_name='Pagaminimo metai')),
                ('valst_nr', models.CharField(max_length=20, verbose_name='Valstybinis numeris')),
            ],
        ),
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=100, verbose_name='Vardas')),
                ('pavarde', models.CharField(max_length=100, verbose_name='Pavardė')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Marke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=100, verbose_name='Markė')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=200, verbose_name='Paslaugos pavadinimas')),
                ('aprasymas', models.TextField(max_length=1300, verbose_name='Paslaugos aprašymas')),
                ('kaina', models.IntegerField(default=0, verbose_name='Paslaugos kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sukurimo_data', models.DateTimeField(blank=True, null=True, verbose_name='Sukurimo data')),
                ('imoketa_suma', models.IntegerField(verbose_name='Įmokėta suma')),
                ('statusas', models.IntegerField(blank=True, choices=[(0, 'Naujas'), (1, 'Vykdomas'), (2, 'Įvykdytas'), (3, 'Atšauktas')], default=0, help_text='Užsakymo statusas', verbose_name='Statusas')),
                ('automobilis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.automobilis')),
            ],
        ),
        migrations.CreateModel(
            name='UzsakymoPrekes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.IntegerField()),
                ('paslauga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.paslauga')),
                ('uzsakymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzsakymo_prekes', to='autoservisas.uzsakymas')),
            ],
        ),
        migrations.CreateModel(
            name='Modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelis', models.CharField(max_length=100, verbose_name='Modelis')),
                ('marke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.marke')),
            ],
        ),
        migrations.AddField(
            model_name='automobilis',
            name='klientas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.klientas'),
        ),
        migrations.AddField(
            model_name='automobilis',
            name='modelis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.modelis'),
        ),
    ]
