# Generated by Django 4.2.18 on 2025-02-03 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='sukurimo_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Sukurimo data'),
        ),
    ]
