# Generated by Django 4.2.18 on 2025-02-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0002_alter_uzsakymas_sukurimo_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='klientas',
            options={'verbose_name': 'Klientas', 'verbose_name_plural': 'Klientai'},
        ),
        migrations.AlterModelOptions(
            name='modelis',
            options={'verbose_name': 'Modelis', 'verbose_name_plural': 'Modeliai'},
        ),
        migrations.AlterModelOptions(
            name='paslauga',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'verbose_name': 'Uzsakymas', 'verbose_name_plural': 'Uzsakymai'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymoprekes',
            options={'verbose_name': 'Uzsakymo_Preke', 'verbose_name_plural': 'Uzsakymų_Prekes'},
        ),
    ]
