# Generated by Django 4.2.18 on 2025-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0003_alter_automobilis_options_alter_klientas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto', verbose_name='Foto'),
        ),
    ]
