# Generated by Django 4.2.18 on 2025-02-10 14:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0006_uzsakymas_grazinimo_terminas'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='aprasymas',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
